Add mangling for fixed point types proposed in N1169.
itanium-cxx-abi/cxx-abi pull request #161
Opened 2023-02-24 20:07 UTC by PiJoules

2023-02-24 20:10 UTC, PiJoules commented
Not sure how to "reference" issues with PRs, but this is for issue https://github.com/itanium-cxx-abi/cxx-abi/issues/56

2023-05-09 15:31 UTC, zygoloid commented on abi.html
> +processors, notabely including support for fixed point arithmetic.
```suggestion
processors, notably including support for fixed point arithmetic.
```

2023-05-09 21:56 UTC, PiJoules commented on abi.html
> +processors, notabely including support for fixed point arithmetic.
Updated

2023-05-10 15:57 UTC, rjmccall requested changes
Generally looks good to me; just a couple minor editorial requests.

We have an active PR in #159 to make certain extended types substitutable.  Should these be substitution candidates if the same type is used in multiple places?

2023-05-10 15:57 UTC, rjmccall commented on abi.html
> +                 ::= [DS] DA <fixed-point-size> # [_Sat] T _Accum
```suggestion
                 ::= [DS] DA <fixed-point-size> # N1169 fixed-point [_Sat] T _Accum
```

2023-05-10 15:57 UTC, rjmccall commented on abi.html
> +                 ::= [DS] DR <fixed-point-size> # [_Sat] T _Fract
```suggestion
                 ::= [DS] DR <fixed-point-size> # N1169 fixed-point [_Sat] T _Fract
```

2023-05-12 01:18 UTC, PiJoules commented on abi.html
> +                 ::= [DS] DR <fixed-point-size> # [_Sat] T _Fract
Done

2023-05-12 01:18 UTC, PiJoules commented on abi.html
> +                 ::= [DS] DA <fixed-point-size> # [_Sat] T _Accum
Done

2023-05-12 01:24 UTC, PiJoules commented
> We have an active PR in #159 to make certain extended types substitutable. Should these be substitution candidates if the same type is used in multiple places?

I asked around and we unfortunately don't know how common it would be to have mangled signatures with fixed-point types in them in places we might intend to use them. Sorry for the incomplete answer. Although given that the largest mangling for a fixed-point type is 5 characters and substitutions should be less than that, we still think having a sub should provide savings.

2023-05-12 15:54 UTC, rjmccall commented
Okay.  The abstract guideline here is that adding substitutions does have a cost: in longer symbols, it can actually increase overall symbol size by filling the substitution table with a lot of extra types, making later substitutions larger.  I would say the line is around 4 bytes — a 3-byte mangling is probably not worth substituting, but a 5-byte mangling probably is.

Applying that to this would make only the saturating types candidates.  But treating different fixed-point types differently might be annoying to implement, and it's probably not a big deal either way.

Given that, do you have a strong opinion?

2023-09-22 20:40 UTC, PiJoules commented
*ping* for any more comments on this

2023-09-22 20:54 UTC, zygoloid commented
Looks good to me.

2023-09-22 20:57 UTC, PiJoules reviewed
Done

2023-09-26 17:44 UTC, rjmccall commented
Alright, I think this has been open for long enough.

2023-09-26 17:44 UTC, merged